"""Added farmerid and phone fields

Revision ID: ddb99ff3001b
Revises: 
Create Date: 2025-04-01 23:04:55.711992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb99ff3001b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.drop_column('birth_date')
        batch_op.drop_column('photo')
        batch_op.drop_column('notes')
        batch_op.drop_column('gender')
        batch_op.drop_column('height')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmerid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))
        batch_op.create_unique_constraint(None, ['farmerid'])
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')
        batch_op.drop_column('farmerid')

    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
